package bench;
import java.util.ArrayList;
import java.util.Random;


public class User extends Thread{
    private seqMessageBoard messageBoard;
    private String username;
    
    public User(seqMessageBoard messageBoard, String username) {
        this.messageBoard = messageBoard;
        this.username = username;
    }
     @Override
     public void run() {
            int numOfPosts = 1 + (int)(Math.random() * ((3 - 2) + 1));
            for (int i = 0; i <= numOfPosts; i++) {
                Random random = new Random();
                String message = generateMessage();
                messageBoard.writeMessage(message);
                System.out.println(username + " posted: " + message);
        

                //Read Messages?
                    int isRead = 0 + (int)(Math.random() * ((1 - 0) + 1));
                if(isRead == 1){
                    ArrayList<String> messages = messageBoard.readMessages();
                    System.out.println(username + " read messages: " + messages);
                }
                    int delay = random.nextInt(5000); // Random delay between 0 and 5 seconds
                    try {
                        Thread.sleep(delay);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                
                
            }
     }

     public String generateMessage(){
        String[] potentialMessages = {
            "Hello, world!",
            "How's everyone doing today?",
            "This is a random message.",
            "I love this message board!",
            "Great job on the project!",
            "What's for lunch?",
            "It's a beautiful day outside.",
            "I need some coffee.",
            "I can't believe it's already Friday!",
            "Has anyone seen my keys?",
            "Let's get to work!",
            "I'm feeling creative today.",
            "Learning is a lifelong journey.",
            "How do you do?",
            "Coffee is life.",
            "Coding is fun!",
            "Don't forget to stay hydrated.",
            "What's your favorite book?",
            "I'm feeling motivated.",
            "Let's make it a productive day!",
            "Life is full of surprises.",
            "Do your best and forget the rest.",
            "The early bird catches the worm.",
            "Learning something new every day.",
            "Stay positive and keep smiling.",
            "Coding is my passion.",
            "Excited to start the day!",
            "Coffee and code, a perfect combo!",
            "What's your favorite programming language?",
            "Stay curious and keep exploring.",
            "Life is an adventure, enjoy it!",
            "Time to make some great code.",
            "Keep calm and keep coding.",
            "Programming is an art.",
            "Success is the sum of small efforts.",
            "Never stop learning.",
            "Positive vibes only.",
            "Work hard, dream big.",
            "Stay focused and never give up.",
            "The journey is the reward.",
            "Live, laugh, code.",
            "Einstein was a developer too!",
            "Embrace the challenge.",
            "Stay hungry, stay foolish.",
            "Dream big, code hard.",
            "Coding is the language of the future.",
            "Coffee, code, repeat.",
            "I'm a bug hunter!",
            "Love what you do.",
            "Innovate, don't imitate.",
            "Code with heart and soul.",
            "Let's change the world with code.",
            "Success is not for the lazy.",
            "Stay curious, stay humble.",
            "Programmers make the world go round.",
            "Geek by nature, programmer by choice.",
            "The code is my canvas.",
            "Keep coding and carry on.",
            "Failure is the key to success.",
            "Coding is like magic.",
            "I speak Java fluently.",
            "Keep coding, keep moving forward.",
            "Love your bugs; they make you better.",
            "Code hard or go home.",
            "Code, coffee, sleep, repeat.",
            "I have a date with my IDE.",
            "Keep calm and trust your code.",
            "I code therefore I am.",
            "Real programmers don't write specs.",
            "The code is strong with this one.",
            "Just keep coding.",
            "There is no place like 127.0.0.1.",
            "Coding is poetry in motion.",
            "I see dead code.",
            "I write code to be happy.",
            "I'm a byte-sized developer.",
            "Code is my superpower.",
            "I'm a code warrior.",
            "I'm not a coder. I'm a programmer.",
            "I code, therefore I exist.",
            "The code must flow.",
            "Ctrl + Alt + Defeat!",
            "It's not a bug; it's a feature.",
            "I'm debugging my life.",
            "Coffee in one hand, code in the other.",
            "Live to code, code to live.",
            "Eat, sleep, code, repeat.",
            "I'm coding with my coffee.",
            "I'm debugging my way to success.",
            "Coffee first, code later.",
            "I'm not a coder; I'm a code breaker.",
            "This is not a bug; it's a feature request.",
            "I'm a code craftsman.",
            "Code is the universal language.",
            "Programming is my cardio.",
            "I'm in a code relationship.",
            "Real programmers don't use mice.",
            "Coders code, testers test.",
            "Happiness is a syntax error.",
            "Coding makes the world go round.",
            "Programmers never die; they just go offline.",
            "Geek. Programmer. Nerd.",
            "I'm a code architect.",
            "Keep coding and carry on.",
            "I'm a code poet.",
            "I write, therefore I code.",
            "Programming is my therapy.",
            "I'm coding my destiny.",
            "Java is my spirit animal.",
            "I'm a bug hunter!",
            "Code like there's no tomorrow.",
            "Eat, sleep, code, repeat.",
            "I'm debugging my life.",
            "Coffee in one hand, code in the other.",
            "Live to code, code to live.",
            "Coding is my superpower.",
            "I'm not a coder; I'm a code breaker.",
            "This is not a bug; it's a feature request.",
            "I'm a code craftsman.",
            "Code is the universal language.",
            "Programming is my cardio.",
            "I'm in a code relationship.",
            "Real programmers don't use mice.",
            "Coders code, testers test.",
            "Happiness is a syntax error.",
            "Coding makes the world go round.",
            "Programmers never die; they just go offline.",
            "Geek. Programmer. Nerd.",
            "I'm a code architect.",
            "Keep coding and carry on.",
            "I'm a code poet.",
            "I write, therefore I code.",
            "Programming is my therapy.",
            "I'm coding my destiny.",
            "Java is my spirit animal.",
            "I'm a bug hunter!",
            "Code like there's no tomorrow.",
            "Stay positive, stay coding.",
            "I'm a code virtuoso.",
            "Coding is my life's work.",
            "I'm a code ninja.",
            "Great coders write code; exceptional coders steal it.",
            "The code is strong with this one.",
            "It's not a bug; it's a feature.",
            "Debugging is like hunting.",
            "I'm a code wizard.",
            "Success is 99% perspiration and 1% coding.",
            "Coding is an art form.",
            "Java is the coffee of programmers.",
            "I code, therefore I am.",
            "Failure is not an option.",
            "Coding is my meditation.",
            "Bug-free code is an illusion.",
            "I'm a software superhero.",
            "Code is the answer to everything.",
            "I'm coding the future.",
            "To code or not to code, that is the question.",
            "Code is the language of the future.",
            "I code; therefore, I am.",
            "I'm a code junkie.",
            "Good code, good life.",
            "Coders do it byte by byte.",
            "Coding is my passion.",
            "I'm a code breaker.",
            "Keep calm and write code.",
            "Code is love, code is life.",
            "Coders can read between the lines.",
            "I'm a pixel warrior.",
            "Code. Sleep. Repeat.",
            "Code it, ship it, repeat it.",
            "Code keeps the lights on.",
            "I'm a code composer.",
            "Elegance in code.",
            "Code is my playground.",
            "I'm a code explorer.",
            "I'm coding the way to success.",
            "I'm in love with my code.",
            "I'm a code artist.",
            "I speak the language of code.",
            "Code like there's no tomorrow.",
            "I'm a code connoisseur.",
            "Code, test, repeat.",
            "I'm a code legend.",
            "Code is my weapon.",
            "I'm a code warrior.",
            "I'm not a coder; I'm a programmer.",
            "I code, therefore I exist.",
            "The code must flow.",
            "Ctrl + Alt + Defeat!",
            "It's not a bug; it's a feature.",
            "I'm debugging my way to success.",
            "Coffee first, code later.",
            "I'm not a coder; I'm a code breaker.",
            "This is not a bug; it's a feature request.",
            "I'm a code craftsman.",
            "Code is the universal language.",
            "Programming is my cardio.",
            "I'm in a code relationship.",
            "Real programmers don't use mice.",
            "Coders code, testers test.",
            "Happiness is a syntax error.",
            "Coding makes the world go round.",
            "Programmers never die; they just go offline.",
            "Geek. Programmer. Nerd.",
            "I'm a code architect.",
            "Keep coding and carry on.",
            "I'm a code poet.",
            "I write, therefore I code.",
            "Programming is my therapy.",
            "I'm coding my destiny.",
            "Java is my spirit animal.",
            "I'm a bug hunter!",
            "Code like there's no tomorrow.",
            "Stay positive, stay coding.",
            "I'm a code virtuoso.",
            "Coding is my life's work.",
            "I'm a code ninja.",
            "Great coders write code; exceptional coders steal it.",
            "The code is strong with this one.",
            "It's not a bug; it's a feature.",
            "Debugging is like hunting.",
            "I'm a code wizard.",
            "Success is 99% perspiration and 1% coding.",
            "Coding is an art form.",
            "Java is the coffee of programmers.",
            "I code, therefore I am.",
            "Failure is not an option.",
            "Coding is my meditation.",
            "Bug-free code is an illusion.",
            "I'm a software superhero.",
            "Code is the answer to everything.",
            "I'm coding the future.",
            "To code or not to code, that is the question.",
            "Code is the language of the future.",
            "I code; therefore, I am.",
            "I'm a code junkie.",
            "Good code, good life.",
            "Coders do it byte by byte.",
            "Coding is my passion.",
            "I'm a code breaker.",
            "Keep calm and write code.",
            "Code is love, code is life.",
            "Coders can read between the lines.",
            "I'm a pixel warrior.",
            "Code. Sleep. Repeat.",
            "Code it, ship it, repeat it.",
            "Code keeps the lights on.",
            "I'm a code composer.",
            "Elegance in code.",
            "Code is my playground.",
            "I'm a code explorer.",
            "I'm coding the way to success.",
            "I'm in love with my code.",
            "I'm a code artist.",
            "I speak the language of code.",
            "Code like there's no tomorrow.",
            "I'm a code connoisseur.",
            "Code, test, repeat.",
            "I'm a code legend.",
            "Code is my weapon.",
            "I'm a code warrior.",
            "I'm not a coder; I'm a programmer.",
            "I code, therefore I exist.",
            "The code must flow.",
            "Ctrl + Alt + Defeat!",
            "It's not a bug; it's a feature.",
            "I'm debugging my way to success.",
            "Coffee first, code later.",
            "I'm not a coder; I'm a code breaker.",
            "This is not a bug; it's a feature request.",
            "I'm a code craftsman.",
            "Code is the universal language.",
            "Programming is my cardio.",
            "I'm in a code relationship.",
            "Real programmers don't use mice.",
            "Coders code, testers test.",
            "Happiness is a syntax error.",
            "Coding makes the world go round."};
        
        return potentialMessages[(int)(Math.random() * ((potentialMessages.length) + 1))];
     }
}
